version: '3.7'

########################--------Bases de données------------#####################

# Les bases de données qu'on va utilisées comme sources initiales des données 
# mongo , postgres, mysql, cassandra
services:
    mongodb:
      image: mongo:6
      container_name: mongo_collecte365 
      ports:
        - 27025:27017  
      volumes:
       - ./Donnees_sources_bd/Mongodata:/data/db  
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin  
      restart: unless-stopped 

    mongo-express:
      image: mongo-express
      container_name: mongo-express_365
      ports:
        - 9088:8081
      environment:
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_BASICAUTH_USERNAME=admin
        - ME_CONFIG_BASICAUTH_PASSWORD=admin
      restart: unless-stopped
      depends_on:
        - mongodb

    
    postgres: 
       image:  postgres:13
       container_name: postgres_collecte365
       ports:
         - "5445:5432"
       environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: post_db_collect 
       volumes:
         - ./Donnees_sources_bd/Postgres:/var/lib/postgresql/data 
       restart: unless-stopped 
    mysql: 
      image: mysql:latest 
      container_name: mysql_collecte365
      environment:
         MYSQL_DATABASE: mysql_db_collecte
         MYSQL_PASSWORD: admin 
         MYSQL_ROOT_PASSWORD: admin
      ports:
        - "3310:3306"
      volumes:
        - ./Donnees_sources_bd/mysql:/var/lib/mysql  
      restart: unless-stopped
    
    cassandra:
        image: cassandra:4.1
        container_name: cassandra365
        ports:
          - "9055:9042"
        environment:
          - CASSANDRA_CLUSTER_NAME=dev-cluster
          - CASSANDRA_DC=datacenter1
          - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
          - CASSANDRA_NUM_TOKENS=256
          - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
          - CASSANDRA_AUTHORIZER=CassandraAuthorizer
          - CASSANDRA_SUPERUSER_NAME=admin
          - CASSANDRA_SUPERUSER_PASSWORD=admin        
        volumes:
          - ./Donnees_sources_bd/cassandra:/var/lib/cassandra  
        restart: unless-stopped
  

    neo4j_de_ben:      
        image: neo4j:5.20
        container_name: neo4j_collecte365
        ports:
          - "7475:7474"  
          - "7688:7687"   
        environment:
          - NEO4J_AUTH=neo4j/admin
        
        volumes: 
          - ./Donnees_sources_bd/neo4j/neo4j-data:/data 
          -  ./Donnees_sources_bd/neo4j/neo4j-logs:/logs
          -  ./Donnees_sources_bd/neo4j/neo4j-import:/var/lib/neo4j/import
          -  ./Donnees_sources_bd/neo4j/neo4j-plugins:/plugins
        restart: unless-stopped  


###################----------- DataLake ---------######-----------#################
    namenode:
      image: apache/hadoop:3.3.5
      container_name: namenode_datalake1
      hostname: namenode
      command: ["hdfs", "namenode"] 
      ports:
        - 9870:9870
        - 8020:8020  # ← Port pour connexions HDFS
      env_file:
        - ./Donnees_sources_bd/hadoop/config
      environment:
        ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      volumes:
        - ./hadoop_namenode:/tmp/hadoop-root/dfs/name

    datanode:
      image: apache/hadoop:3.3.5
      container_name: datanode_datalake1
      hostname: datanode
      command: ["hdfs", "datanode"]
      ports:
        - "9864:9864"  # ← Port WebHDFS du datanode
        - "9866:9866"  # ← Port de données du datanode
        - "9867:9867"  # ← Port IPC du datanode
      env_file:
        - ./Donnees_sources_bd/hadoop/config
      volumes:
        - ./hadoop_datanode:/tmp/hadoop-root/dfs/data
      depends_on:
        - namenode

    resourcemanager:
      image: apache/hadoop:3.3.5
      container_name: ressource_datalake1
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
        - 8088:8088 
      env_file:
        - ./Donnees_sources_bd/hadoop/config
      volumes:
        - ./Donnees_sources_bd/hadoop/test.sh:/opt/test.sh
      depends_on:
        - namenode

    nodemanager:
      image: apache/hadoop:3.3.5
      container_name: node_manager_datalake1
      hostname: nodemanager
      command: ["yarn", "nodemanager"]
      env_file:
        - ./Donnees_sources_bd/hadoop/config
      depends_on:
        - namenode
        - resourcemanager


    spark-master:
      image: bitnami/spark:latest
      container_name: spark-maitre
      environment:
        - SPARK_MODE=master
        - SPARK_RPC_AUTHENTICATION_ENABLED=no
        - SPARK_RPC_ENCRYPTION_ENABLED=no
        - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
        - SPARK_SSL_ENABLED=no
      ports:
        - "7077:7077"   
        - "8082:8080"   

    spark-worker:
      image: bitnami/spark:latest
      container_name: spark-worker
      environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark-master:7077
        - SPARK_WORKER_MEMORY=2G
        - SPARK_WORKER_CORES=2
      depends_on:
        - spark-master
      ports:
        - "8086:8081"  

      ###---------- Orchestration avec Airflow ---------------#######
    postgresJob:
     image: postgres:13
     container_name: postgres_dag_job365
     environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
    airflow-db-init:
      #image: apache/airflow:2.9.0
      build:
        context: .
        dockerfile: ./Airflow/Dockerfile 
      image: airflow-avec-pyspark
      depends_on:
        - postgresJob
      env_file:
        - .env 
      environment:
          AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
          AIRFLOW__WEBSERVER__SECRET_KEY: '34f9a2c7e6b94b11a3f9a6b5a2c7d1e2'
          AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
          AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_LOCATION: /opt/airflow/logs/dag_processor_manager/dag_processor_manager.log
          PYTHONPATH: /opt/airflow/src
      volumes:
        - ./Airflow/dags:/opt/airflow/dags
        - ./Airflow/logs:/opt/airflow/logs
        - /etc/localtime:/etc/localtime:ro
        

      entrypoint: 
        bash -c " airflow db init && 
        airflow db migrate && 
        airflow users create \
          --username ${username} \
          --password ${password} \
          --firstname ${firstname} \
          --lastname ${lastname} \
          --role ${role} \
          --email ${email}"
    
    # interface graphique de airflow 
    airflow-webserver:
      #image: apache/airflow:2.9.0
      build:
        context: .
        dockerfile: ./Airflow/Dockerfile 
      image: airflow-with-pyspark
      container_name: airflow_web365
      ports:
        - ${Port_externe_Airflow}:8080  
      depends_on:
        - postgresJob
      env_file:
        - .env 
      environment:
          AIRFLOW__CORE__EXECUTOR: LocalExecutor
          AIRFLOW__CORE__PARALLELISM: 32 # nombre dag a lancer en parallele  
          AIRFLOW__CORE__DAG_CONCURRENCY: 16  #nombre de tache a lancer en parallele par dag 
          AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 16
          AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
          AIRFLOW__WEBSERVER__SECRET_KEY: '34f9a2c7e6b94b11a3f9a6b5a2c7d1e2'
          AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
          AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_LOCATION: /opt/airflow/logs/dag_processor_manager/dag_processor_manager.log
          PYTHONPATH: /opt/airflow/src   
      volumes:
        - ./Airflow/dags:/opt/airflow/dags
        - ./Airflow/logs:/opt/airflow/logs
        - /etc/localtime:/etc/localtime:ro

      command: airflow webserver

    # gestionnaires des taches automatiquement (avec scheduler)
    airflow-scheduler: 
      #image: apache/airflow:2.9.0
      build:
          context: .
          dockerfile: ./Airflow/Dockerfile 
      image: airflow-avec-pyspark
      container_name: mon_schedulerjob365
      restart: always 
      depends_on:
        - airflow-webserver
      env_file:
        - .env 
      volumes:
        - ./Airflow/dags:/opt/airflow/dags
        - ./Airflow/logs:/opt/airflow/logs
        - /etc/localtime:/etc/localtime:ro
      environment:
            AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
            AIRFLOW__WEBSERVER__SECRET_KEY: '34f9a2c7e6b94b11a3f9a6b5a2c7d1e2'
            AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
            AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_LOCATION: /opt/airflow/logs/dag_processor_manager/dag_processor_manager.log
            PYTHONPATH: /opt/airflow/src
      command: airflow scheduler 


